{{- if .Values.component.MCPServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prodrecmcp
  labels:
    app: {{ .Release.Name }}-{{ .Values.component.name }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    impl: {{ .Release.Name }}-prodrecmcp
  ports:
    - port: 8080
      targetPort: {{ .Release.Name }}-pomcp
      name: http-{{ .Release.Name }}-prodrecmcp
{{- end }}
