apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prodrecapi
  labels:
    app: {{ .Release.Name }}-{{ .Values.component.name }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    impl: {{ .Release.Name }}-prodrecapi
  ports:
    - port: 8080
      targetPort: {{ .Release.Name }}-prdapi
      name: http-{{ .Release.Name }}-prodrecapi
