apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-troubleticketmanagementengine
  labels:
    app: {{ .Release.Name }}-{{ .Values.component.name }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  type: ClusterIP
  selector:
    impl: {{ .Release.Name }}-troubleticketmanagementengine
  ports:
    - port: 8081
      targetPort: {{ .Release.Name }}-pmeng
      name: http-{{ .Release.Name }}-troubleticketmanagementengine
