{{- if .Values.engine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-productcatalogengine
  labels:
    app: {{ .Release.Name }}-{{ .Values.component.name }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  type: ClusterIP
  selector:
    impl: {{ .Release.Name }}-productcatalogengine
  ports:
    - port: 8081
      targetPort: {{ .Release.Name }}-pceng
      name: http-{{ .Release.Name }}-productcatalogengine
{{- end }}
