apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ordervalidation
  labels:
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{ .Release.Name }}-ordervalidation
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.component.name }}
        impl: {{ .Release.Name }}-ordervalidation
        version: {{ .Values.validation.versionLabel }}
    spec:
      containers:
        - name: {{ .Release.Name }}-ordervalidation
          image: {{ .Values.validation.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Release.Name }}-oval
              containerPort: 8081
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20

