kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongodb-pv-claim
  labels:
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  {{- with .Values.component.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
