apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.component.name }}-sm
  labels:
    name: {{ .Release.Name }}-{{ .Values.component.name }}-sm
    app: {{ .Release.Name }}-{{ .Values.component.name }}
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    impl: {{ .Release.Name }}-metricsapi
  ports:
    - port: 4000
      targetPort: {{ .Release.Name }}-mtapi
      name: http-{{ .Release.Name }}-{{ .Values.component.name }}-sm

