# Default values for productordercapturevalidation.

component:
  id: TMFC002
  name: productordercapturevalidation
  functionalBlock: CoreCommerce
  publicationDate: 2026-03-14T00:00:00.000Z
  version: "0.4.0"
  apiVersion: v4
  specificationUrl: https://raw.githubusercontent.com/tmforum-apis/TMF622_ProductOrder/main/TMF622-ProductOrder-v4.0.0.swagger.json
  mcpSpecificationUrl: https://modelcontextprotocol.io/specification/
  storageClassName: ""
  apipolicy:
    apiKeyVerification:
      enabled: false
      location: header
    rateLimit:
      enabled: false
      identifier: IP
      limit: "6"
      interval: pm
    quota:
      identifier: ""
      limit: ""
    OASValidation:
      requestEnabled: false
      responseEnabled: false
      allowUnspecifiedHeaders: false
      allowUnspecifiedQueryParams: false
      allowUnspecifiedCookies: false
    CORS:
      enabled: false
      allowCredentials: false
      allowOrigins: "https://allowed-origin.com, https://allowed-origin2.com"
      handlePreflightRequests:
        enabled: false
        allowHeaders: "Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"
        allowMethods: "GET, POST, PATCH, DELETE"
        maxAge: 36000
    template: ""
  dependentAPIs:
    enabled: false
    catalog:
      name: productcatalogmanagement
      specificationUrl: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
  eventNotification:
    publishedEvents:
      - ProductOrderCreateEvent
      - ProductOrderAttributeValueChangeEvent
      - ProductOrderDeleteEvent
      - ProductOrderStateChangeEvent
      - ProductOrderInformationRequiredEvent
      - CancelProductOrderCreateEvent
      - CancelProductOrderStateChangeEvent
      - CancelProductOrderInformationRequiredEvent
    subscribedEvents: []
  MCPServer:
    enabled: true

security:
  canvasSystemRole: ProductOrderAdmin

service:
  type: NodePort

mongodb:
  image: mongo:7
  port: 27017
  database: tmfc002
  storage: 5Gi

api:
  image: ravijangra92/tmf622:product-order-api-1.1
  versionLabel: product-order-api-1.1

validation:
  image: ravijangra92/tmf622:order-validation-1.1
  versionLabel: order-validation-1.1

metrics:
  image: ravijangra92/tmf622:open-metrics-1.2
  versionLabel: open-metrics-1.2

mcp:
  image: ravijangra92/tmf622:mcp-server-1.3
  versionLabel: mcp-server-1.3

partyrole:
  image: ravijangra92/tmf622:party-role-1.2
  versionLabel: party-role-1.2

roleinitialization:
  image: ravijangra92/tmf622:role-init-1.1
  versionLabel: role-init-1.1

productorderinitialization:
  image: ravijangra92/tmf622:product-order-init-1.1
  versionLabel: product-order-init-1.1
